version: '2'
services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  app:
    build: .
    image: wiki-app
    command: bin/docker-start
    env_file:
      - .env
    links:
      - postgres
      - redis
    volumes:
      - .:/var/www/wiki_application
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
volumes:
  postgres: {}
  redis: {}
